### ISSUE TITLE
Great tutorial, only one detail

### ISSUE THREAD

**Issue by deni2312** [DaveH355/clustered-shading#1]
Hi Dave, so far one of the best tutorials i've ever read about clustered shading, one precisation(tell me if i am wrong) in the README where you specify numClusters you mean gridSizeX * gridSizeY * gridSizeZ right? If so the rest looks good and i've succesfully implemented in my engine.
Thanks and yes this really should be integrated in learnopengl.com

**Comment by DaveH355** [comment]
Hey thanks for the issue. Glad to hear you've implemented this in your engine!  Yes `numClusters = gridSizeX * gridSizeY * gridSizeZ`. It should be defined in the C++ code but somehow slipped through the cracks.

**Comment by DaveH355** [comment]
fixed it :)
